public class DetailDisplay{
    
   
    public String model{get; set;}
    public String color{get; set;}
    public String descreption{get; set;}
    public String productType{get; set;}
    public String productFamily{get; set;}
    public String qty{get; set;}
    public String retailerCodeName{get; set;}
    public String modelRemark{get; set;}
    public String price100pcs{get;set;}
    public String localCurrency{get;set;}
    public String salesValueInLocalCurrency{get;set;}
    public String productImage{get;set;}
    public DetailDisplay(){
        
    }
    

}