public class summaryQuantityObj {
   
   
    public Double quantity;
    public Date weekStartDate;
    public Date weekEndDate;
    
        
    public Double getQuantity()
    {
        return quantity;
    }
    public void setTotalDemandQty(Double quantity)
    {
        this.quantity=quantity;
    } 
    public Date getWeekStartDate()
    {
        return weekStartDate;
    }
    public void setWeekStartDate(Date weekStartDate)
    {
        this.weekStartDate=weekStartDate;
    } 
   public Date getWeekEndDate()
    {
        return weekEndDate;
    }
    public void setWeekEndDate(Date weekEndDate)
    {
        this.weekEndDate=weekEndDate;
    } 
    
}